### ISSUE TITLE
Webpage text selection

### ISSUE THREAD

**Issue by mattverley** [YvesPhilippot/Goat-clicker#1]
In order to avoid text selection on the webpage when double/triple clicking, use these lines on the elements to impact :

``` css
.noselect {
-webkit-user-select: none;  /* Chrome all / Safari all */
-moz-user-select: none;     /* Firefox all */
-ms-user-select: none;      /* IE 10+ */
/* No support for these yet, use at own risk */
-o-user-select: none;
user-select: none;
}
```

This will ensure fast-no-selecting-hellish-madness!
